config:
  tools:
    gcp:
      params:
        image: aroq/toolbox-cloud:0.1.5
        tool_dirs:
          - toolbox/.toolbox/deps/toolbox-gcp

tools:
  gcp:
    from: config.tools.gcp
    cmd: gcp

